services:
  db:
    image: postgres:16
    container_name: pulse
    restart: unless-stopped
    environment:
      POSTGRES_USER: pulse
      POSTGRES_PASSWORD: pulse_pass
      POSTGRES_DB: pulse_db
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U pulse -d pulse_db']
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
